services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt-challenge-api
    ports:
      - "2137:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017
      - AI__OpenAI__ApiKey=${OPENAI_API_KEY}
      - AI__Gemini__ApiKey=${GEMINI_API_KEY}
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge